---

docker_package: docker-ce
docker_package_version: '=5:19.03.*'
docker_package_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
docker_package_hold: install
docker_apt_key_url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
docker_apt_repository: 'deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
docker_compose_install: yes
docker_compose_update: no
docker_compose_version: 1.25.0
docker_compose_download: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
docker_options:
  debug: false
  log-level: error
