---

- name: restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted

- name: recreate kube-dns
  command: kubectl --kubeconfig={{ kubernetes_kubeadmin_config }} -n kube-system delete pods -l k8s-app=kube-dns
  delegate_to: "{{ groups['kubernetes_master'][0] }}"
  run_once: true
  ignore_errors: true
