---

- name: Configure APT
  template:
    src: etc/apt/apt.conf.d/99local
    dest: /etc/apt/apt.conf.d/99local
    owner: root
    group: root
    mode: 0644

- name: Add APT default source list
  template:
    src: etc/apt/sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: Update APT cache
  apt:
    update_cache: yes
  changed_when: no

- name: Add APT keys from URL
  apt_key:
    url: '{{ item.key_url }}'
    state: '{{ item.state | default("present") }}'
  with_items:
    - '{{ common_apt_repositories }}'
  when: item.key_url is defined and item.key_url

- name: Add APT keys from keyserver
  apt_key:
    id: '{{ item.key_id }}'
    keyserver: '{{ item.key_server }}'
    state: '{{ item.state | default("present") }}'
  with_items:
    - '{{ common_apt_repositories }}'
  when: item.key_id is defined and item.key_id
    and item.key_server is defined and item.key_server

- name: Add APT repositories
  apt_repository:
    repo: '{{ item.repo }}'
    state: '{{ item.state | default("present") }}'
    filename: '{{ item.filename | default(omit) }}'
    update_cache: yes
  with_items:
    - '{{ common_apt_repositories }}'
  when: item.repo is defined and item.repo

- name: Add APT PPA
  apt_repository:
    repo: '{{ item }}'
    update_cache: yes
    filename: '{{ item.filename | default(omit) }}'
  with_items:
    - '{{ common_apt_ppa }}'
  when: common_apt_ppa is defined and common_apt_ppa

- name: Remove packages
  apt:
    name: '{{ common_apt_remove_packages }}'
    state: absent
    purge: yes
  when: common_apt_remove_packages is defined and common_apt_remove_packages

- name: Install packages
  apt:
    name: '{{ common_apt_install_packages | union(common_apt_install_packages_default) }}'
    state: present

- name: Install deb packages
  apt:
    deb: '{{ item }}'
  when: common_apt_install_deb is defined and common_apt_install_deb
  with_items:
    - '{{ common_apt_install_deb }}'

- name: Hold packages
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  when: item is defined and item
  with_items:
    - '{{ common_apt_hold_packages }}'
