---
- hosts: 'ubuntu-kube*:{{ test_host|d() }}'
  tasks:
    - name: Install pip and python-setuptools
      apt:
        name:
          - python-pip
          - python-setuptools
        state: installed