---

galaxy_info:
  author: asakharov
  description: Docker role
  min_ansible_version: 2.2

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: Debian
      versions:
        - jessie

  galaxy_tags: []

dependencies: []
