---

galaxy_info:
  author: asakharov
  description: Kubernetes node role
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
    - name: Debian
      versions:
        - stretch
        - buster

  galaxy_tags: []

dependencies: []
